site_name: Mnemosyne

theme:
  name: readthedocs
  # name: windmill
  #name: 'material'
  # name: flatly
  # name: bootstrap


extra:
  theme_inverse: true



markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: true
    - toc:
        permalink: true
        separator: "_"

extra_javascript: 
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav: 
  - "Home": index.md
  - "A":
    - "GE": a_GE/index.md
    - "Intro": a_GE/intro.md
  # - "B":
  #   - "Hepa": b_Hepa/index.md
  #   - "Intro": b_Hepa/intro.md
  # - "C": 
  #   - "CV": c_CV/index.md
  # - "D": 
  #   - "Endo": d_Endo/index.md
  #   - "Meta": d_Meta/index.md
  # - "E": 
  #   - "Nephro": e_Nephro/index.md
  # - "F":
  #   - "Immune": 
  # - "G":
  #   - "Heme": 
  # - "H":
  #   - "Infxn": 
  # - "I":
  #   - "Pulmo": 
  # - "J":
  #   - "Neuro":
  # - "K":
  #   - "Tox": 
  # - "L": 
  #   - "ER":
  # - "M":
  #   - "Ans":
  # - "N":
  #   - "Geri":
  # - "O":
  #   - "Ped":
  # - "P":
  #   - "OB":
  - "Q":
    # - "GYN": q_GYN
    - "Intro": q_GYN/intro.md
    - "Endocrine": q_GYN/endocrine.md
  # - "R":
  #   - "Oph":
  # - "S":
  #   - "ENT":
  # - "T":
  #   - "Ortho":
  # - "U":
  #   - "&psi;":
  # - "V":
  #   - "Derm":
  # - "W": 
  #   - "GU":
  # - "X":
  #   - "Radio":
  # - "Y":
  #   - "Health":


