site_name: Mnemosyne

theme:
  name: readthedocs
  # name: windmill
  #name: 'material'
  # name: flatly
  # name: bootstrap


extra:
  theme_inverse: true



markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: true
    - toc:
        permalink: true
        separator: "_"

extra_javascript:
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav:
  - "Home": index.md
  - "A GE":
    # - "GE": a_GE/index.md
    - "Intro": a_GE/intro.md
    # - "Oesophagus": a_GE/
    # - "Stomach": a_GE/
    # - "Intestine": a_GE/
    # - "Anus": a_GE/
    # - "Peritoneum": a_GE/
    # - "General": a_GE/
  - "B Hepa":
    # - "Hepa": b_Hepa/index.md
    - "Intro Liver": b_Hepa/intro.md
    # - "Liver": b_Hepa/
    # - "Intro Cholangio": b_Hepa/
    # - "Cholangio": b_Hepa/
    # - "Intro Pancreas": b_Hepa/
    # - "General": b_Hepa/
  - "C CV":
    # - "CV": c_CV/index.md
    - "Intro": c_CV/
    # - "Heart Failure": c_CV/
    # - "Arrhythmia": c_CV/
    # - "Valvulopathy": c_CV/
    # - "Cogenital": c_CV/
    # - "Cardiomyopathy": c_CV/
    # - "Tumor": c_CV/
    # - "Artery": c_CV/
    # - "Pressure": c_CV/
  - "D Endo":
    - "Endo": d_Endo/index.md
    # - "Hypothalamus-Pituitary": d_Endo/
    # - "Adrenal": c_CV/
    # - "Thyroid": c_CV/
    # - "Parathyroid": c_CV/
    # - "Endocrine Tumor": c_CV/
    # - "MEN": c_CV/
    # - "General": c_CV/
  - "D Meta":
    - "Meta": d_Meta/index.md
  - "E Nephro":
    - "Intro": e_Nephro/index.md
  #   - "Nephro": e_Nephro/index.md
  - "F Immune":
  #   - "Immune":
    - "Intro": f_Immune/index.md
  # - "G Heme":
    # - "Heme": g_Heme/index.md
  # - "H Infxn":
  #   - "Infxn":
  # - "I":
  #   - "Pulmo":
  # - "J":
  #   - "Neuro":
  # - "K":
  #   - "Tox":
  # - "L":
  #   - "ER":
  # - "M":
  #   - "Ans":
  # - "N":
  #   - "Geri":
  # - "O":
  #   - "Ped":
  # - "P":
  #   - "OB":
  - "Q GYN":
    # - "GYN": q_GYN
    - "Intro": q_GYN/intro.md
    - "Endocrine": q_GYN/endocrine.md
    # - "Development"
    # - "STI"
    # - "Infertility"
    # - "Aging"
    - "Tumor": q_GYN/tumor.md
    - "General": q_GYN/general.md
  # - "R":
  #   - "Oph":
  # - "S":
  #   - "ENT":
  - "T Ortho":
    - "Ortho": t_Ortho/index.md
  # - "U":
  #   - "&psi;":
  # - "V":
  #   - "Derm":
  # - "W":
  #   - "GU":
  # - "X":
  #   - "Radio":
  # - "Y":
  #   - "Health":
