site_name: MMB

site_url: https://shumez.github.io/mnemosyne/MMB/site

theme:
  name: readthedocs
  # name: windmill
  #name: 'material'
  # name: flatly
  # name: bootstrap

extra:
  theme_inverse: true
  
markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: true
    - toc:
        permalink: true
        separator: "_"
        title: None
        # toc_depth: "2-4"
        # baselevel: 1

extra_javascript:
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav:
  - "Home": index.md
  - "A. GE":
    # - "GE": a_GE/index.md
    - "Intro": a_GE/Intro.md
    - "Oesophagus": a_GE/Oesophagus.md
    - "Stomach": a_GE/Stomach.md
    - "Intestine": a_GE/Intestine.md
    - "Anus": a_GE/Anus.md
    - "Peritoneum": a_GE/Peritoneum.md
    # - "General": a_GE/
  - "B. Hepa":
    # - "Hepa": b_Hepa/index.md
    - "Intro Liver": b_Hepa/IntroLiver.md
    - "Liver": b_Hepa/Liver.md
    - "Intro Cholangio": b_Hepa/IntroCholangio.md
    - "Cholangio": b_Hepa/Cholangio.md
    - "Intro Pancreas": b_Hepa/IntroPancreas.md
    - "Pancreas": b_Hepa/Pancreas.md
    # - "General": b_Hepa/
  - "C. CV":
    # - "CV": c_CV/index.md
    - "Intro": c_CV/Intro.md
    - "Heart Failure": c_CV/HeartFailure.md
    - "Arrhythmia": c_CV/Arrhythmia.md
    - "Valvulopathy": c_CV/Valvulopathy.md
    - "Cogenital": c_CV/Congenital.md
    - "Cardiomyopathy": c_CV/Cardiomyopathy.md
    - "Tumor": c_CV/Tumor.md
    - "Vasculature": c_CV/Vasculature.md
    - "Pressure": c_CV/Pressure.md
  - "D. Endo":
    # - "Endo": d_Endo/index.md
    - "Hypothalamus-Pituitary": d_Endo/Hypothalamus-Pituitary.md
    - "Adrenal": d_Endo/Adrenal.md
    - "Thyroid": d_Endo/Thyroid.md
    - "Parathyroid": d_Endo/Parathyroid.md
    - "Endocrine Tumor": d_Endo/EndocrineTumor.md
    - "MEN": d_Endo/MEN.md
    # - "General": c_CV/
  - "D. Meta":
    # - "Meta": d_Meta/index.md
    - "Carbohydrate": d_Meta/Carbohydrate.md
  - "E. Nephro":
    - "Intro": e_Nephro/Intro.md
    - "Renal Faulure": e_Nephro/RenalFailure.md
    - "Tubule": e_Nephro/Tubule.md
    - "Glomerulus": e_Nephro/Glomerulus.md
    - "Systemic": e_Nephro/Systemic.md
    - "Renovascular": e_Nephro/Renovascular.md
    - "Herediatary": e_Nephro/Hereditary.md
  - "E. Elctr":
    - "Intro": e_Elctr/Intro.md
  - "F. Immune":
    - "Allergy": f_Immune/Allergy.md
    - "Rheumatology": f_Immune/Rheumatology.md
    - "Intro": f_Immune/Intro.md
    - "Immunodeficiency": f_Immune/Immunodeficiency.md
  - "G. Heme":
    - "Intro": g_Heme/Intro.md
  - "H. Infxn":
    - "Pneumonia": h_Infxn/Pneumonia.md
  - "I. Pulmo":
    - "Intro": i_Pulmo/Intro.md
  - "J. Neuro":
    - "Intro": j_Neuro/Intro.md
    - "Cranial Nerve": j_Neuro/CranialNerve.md
    - "Sensorimotor": j_Neuro/Sensorimotor.md
    - "Pressure": j_Neuro/Pressure.md
    - "Hydrocephalus": j_Neuro/Hydrocephalus.md
    - "Cerebrovascular": j_Neuro/Cerebrovascular.md
    - "Brain Stem": j_Neuro/BrainStem.md
    - "Neurodegenerative": j_Neuro/Neurodegenerative.md
    - "Demyelinating": j_Neuro/Demyelinating.md
    - "Neuropathy": j_Neuro/Neuropathy.md
    - "Myopathy": j_Neuro/Myopathy.md
    - "Dementia": j_Neuro/Dementia.md
    - "Tumor": j_Neuro/Tumor.md
    - "Functional": j_Neuro/Functional.md
    - "Infection": j_Neuro/Infection.md
    - "Trauma": j_Neuro/Trauma.md
    - "Metabolism": j_Neuro/Metabolism.md
    - "Malformation": j_Neuro/Malformation.md
  # - "K. Tox":
  #   - "Tox":
  # - "L. ER":
  #   - "ER":
  # - "M. Ans":
  #   - "Ans":
  # - "N":
  #   - "Geri":
  # - "O.Ped":
  #   - "Ped":
  # - "P. OB":
  #   - "OB":
  - "Q. GYN":
    # - "GYN": q_GYN
    - "Intro": q_GYN/Intro.md
    - "Endocrine": q_GYN/Endocrine.md
    # - "Development"
    # - "STI"
    # - "Infertility"
    # - "Aging"
    - "Tumor": q_GYN/Tumor.md
    # - "General": q_GYN/general.md
  # - "R. Oph":
  #   - "Oph":
  # - "S. ENT":
  #   - "ENT":
  # - "T. Ortho":
    # - "Ortho": t_Ortho/index.md
  # - "U. &Psi;":
  #   - "&psi;":
  # - "V. Derm":
  #   - "Derm":
  # - "W. GU":
  #   - "GU":
  # - "X. Radio":
  #   - "Radio":
  # - "Y. Health":
  #   - "Health":